# AP-Workshop7: UML and CRC Design for Taxi and Messenger Applications

## Overview
This workshop focuses on designing UML Class Diagrams and CRC Cards for two applications:
1. **Taxi Service**: Models booking, fare calculation, and ride management.
2. **Messenger**: Simulates user communication and chat management.

## Deliverables
- **UML Diagrams**: Class names, attributes, methods, and relationships.
- **CRC Cards**: Class responsibilities and collaborations.

## Files
- UML Diagrams: `uml_diagrams/Taxi-uml.mermaid`
- CRC Cards: `crc_cards/Messenger.mermaid`

## Tools
- UML Tool: [mermaid live](https://mermaid.live/)

## Author
- [Mustafa Qasimi](https://github.com/mustafaqasimi)